//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesWeb.ProxyLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyLogin.IServicioLogin")]
    public interface IServicioLogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicioLogin/AutenticarUsuarioResponse")]
        bool AutenticarUsuario(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogin/AutenticarUsuario", ReplyAction="http://tempuri.org/IServicioLogin/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> AutenticarUsuarioAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLoginChannel : LosGrisesWeb.ProxyLogin.IServicioLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLoginClient : System.ServiceModel.ClientBase<LosGrisesWeb.ProxyLogin.IServicioLogin>, LosGrisesWeb.ProxyLogin.IServicioLogin {
        
        public ServicioLoginClient() {
        }
        
        public ServicioLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AutenticarUsuario(string username, string password) {
            return base.Channel.AutenticarUsuario(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AutenticarUsuarioAsync(string username, string password) {
            return base.Channel.AutenticarUsuarioAsync(username, password);
        }
    }
}
