//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbLibreriaEntities : DbContext
    {
        public dbLibreriaEntities()
            : base("name=dbLibreriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Almacen> tb_Almacen { get; set; }
        public virtual DbSet<tb_Autor> tb_Autor { get; set; }
        public virtual DbSet<tb_Cliente> tb_Cliente { get; set; }
        public virtual DbSet<tb_Editorial> tb_Editorial { get; set; }
        public virtual DbSet<tb_Ejemplar> tb_Ejemplar { get; set; }
        public virtual DbSet<tb_Genero> tb_Genero { get; set; }
        public virtual DbSet<tb_Libro> tb_Libro { get; set; }
        public virtual DbSet<tb_Personal> tb_Personal { get; set; }
        public virtual DbSet<tb_Renta> tb_Renta { get; set; }
        public virtual DbSet<tb_Requerimiento> tb_Requerimiento { get; set; }
        public virtual DbSet<tb_Requerimiento_detalle> tb_Requerimiento_detalle { get; set; }
        public virtual DbSet<tb_Ubigeo> tb_Ubigeo { get; set; }
        public virtual DbSet<vw_VistaAutor> vw_VistaAutor { get; set; }
        public virtual DbSet<vw_VistaClientes> vw_VistaClientes { get; set; }
        public virtual DbSet<vw_VistaLibro> vw_VistaLibro { get; set; }
        public virtual DbSet<vw_VistaLibrosRentados> vw_VistaLibrosRentados { get; set; }
        public virtual DbSet<vw_VistaRentas> vw_VistaRentas { get; set; }
    
        public virtual ObjectResult<usp_ConsultarAutor_Result> usp_ConsultarAutor(Nullable<int> aut_id)
        {
            var aut_idParameter = aut_id.HasValue ?
                new ObjectParameter("aut_id", aut_id) :
                new ObjectParameter("aut_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarAutor_Result>("usp_ConsultarAutor", aut_idParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCliente_Result> usp_ConsultarCliente(Nullable<int> cli_id)
        {
            var cli_idParameter = cli_id.HasValue ?
                new ObjectParameter("cli_id", cli_id) :
                new ObjectParameter("cli_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCliente_Result>("usp_ConsultarCliente", cli_idParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEjemplaresDisponibles_Result> usp_ConsultarEjemplaresDisponibles(string libroNom)
        {
            var libroNomParameter = libroNom != null ?
                new ObjectParameter("LibroNom", libroNom) :
                new ObjectParameter("LibroNom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEjemplaresDisponibles_Result>("usp_ConsultarEjemplaresDisponibles", libroNomParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarLibro_Result> usp_ConsultarLibro(Nullable<int> lib_id)
        {
            var lib_idParameter = lib_id.HasValue ?
                new ObjectParameter("lib_id", lib_id) :
                new ObjectParameter("lib_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarLibro_Result>("usp_ConsultarLibro", lib_idParameter);
        }
    
        public virtual int usp_EditarAutor(Nullable<int> aut_id, string aut_nom, string aut_ape, string aut_pais, byte[] aut_foto, string aut_user_mod)
        {
            var aut_idParameter = aut_id.HasValue ?
                new ObjectParameter("aut_id", aut_id) :
                new ObjectParameter("aut_id", typeof(int));
    
            var aut_nomParameter = aut_nom != null ?
                new ObjectParameter("aut_nom", aut_nom) :
                new ObjectParameter("aut_nom", typeof(string));
    
            var aut_apeParameter = aut_ape != null ?
                new ObjectParameter("aut_ape", aut_ape) :
                new ObjectParameter("aut_ape", typeof(string));
    
            var aut_paisParameter = aut_pais != null ?
                new ObjectParameter("aut_pais", aut_pais) :
                new ObjectParameter("aut_pais", typeof(string));
    
            var aut_fotoParameter = aut_foto != null ?
                new ObjectParameter("aut_foto", aut_foto) :
                new ObjectParameter("aut_foto", typeof(byte[]));
    
            var aut_user_modParameter = aut_user_mod != null ?
                new ObjectParameter("aut_user_mod", aut_user_mod) :
                new ObjectParameter("aut_user_mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EditarAutor", aut_idParameter, aut_nomParameter, aut_apeParameter, aut_paisParameter, aut_fotoParameter, aut_user_modParameter);
        }
    
        public virtual int usp_EditarCliente(Nullable<int> cli_id, string cli_nom, string cli_ape, string cli_dir, string cli_tel, string cli_mail, string cli_dni, string ubg_id, Nullable<System.DateTime> cli_fec_nac, string cli_sex, byte[] cli_foto, string cli_user_mod, Nullable<bool> cli_state)
        {
            var cli_idParameter = cli_id.HasValue ?
                new ObjectParameter("cli_id", cli_id) :
                new ObjectParameter("cli_id", typeof(int));
    
            var cli_nomParameter = cli_nom != null ?
                new ObjectParameter("cli_nom", cli_nom) :
                new ObjectParameter("cli_nom", typeof(string));
    
            var cli_apeParameter = cli_ape != null ?
                new ObjectParameter("cli_ape", cli_ape) :
                new ObjectParameter("cli_ape", typeof(string));
    
            var cli_dirParameter = cli_dir != null ?
                new ObjectParameter("cli_dir", cli_dir) :
                new ObjectParameter("cli_dir", typeof(string));
    
            var cli_telParameter = cli_tel != null ?
                new ObjectParameter("cli_tel", cli_tel) :
                new ObjectParameter("cli_tel", typeof(string));
    
            var cli_mailParameter = cli_mail != null ?
                new ObjectParameter("cli_mail", cli_mail) :
                new ObjectParameter("cli_mail", typeof(string));
    
            var cli_dniParameter = cli_dni != null ?
                new ObjectParameter("cli_dni", cli_dni) :
                new ObjectParameter("cli_dni", typeof(string));
    
            var ubg_idParameter = ubg_id != null ?
                new ObjectParameter("ubg_id", ubg_id) :
                new ObjectParameter("ubg_id", typeof(string));
    
            var cli_fec_nacParameter = cli_fec_nac.HasValue ?
                new ObjectParameter("cli_fec_nac", cli_fec_nac) :
                new ObjectParameter("cli_fec_nac", typeof(System.DateTime));
    
            var cli_sexParameter = cli_sex != null ?
                new ObjectParameter("cli_sex", cli_sex) :
                new ObjectParameter("cli_sex", typeof(string));
    
            var cli_fotoParameter = cli_foto != null ?
                new ObjectParameter("cli_foto", cli_foto) :
                new ObjectParameter("cli_foto", typeof(byte[]));
    
            var cli_user_modParameter = cli_user_mod != null ?
                new ObjectParameter("cli_user_mod", cli_user_mod) :
                new ObjectParameter("cli_user_mod", typeof(string));
    
            var cli_stateParameter = cli_state.HasValue ?
                new ObjectParameter("cli_state", cli_state) :
                new ObjectParameter("cli_state", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EditarCliente", cli_idParameter, cli_nomParameter, cli_apeParameter, cli_dirParameter, cli_telParameter, cli_mailParameter, cli_dniParameter, ubg_idParameter, cli_fec_nacParameter, cli_sexParameter, cli_fotoParameter, cli_user_modParameter, cli_stateParameter);
        }
    
        public virtual int usp_EditarLibro(Nullable<int> lib_id, string lib_nom, Nullable<int> aut_id, Nullable<int> gen_id, string lib_edi, Nullable<int> lib_fec_pub, Nullable<int> lib_disp_stock, Nullable<int> edi_id, string lib_user_mod, Nullable<bool> lib_state)
        {
            var lib_idParameter = lib_id.HasValue ?
                new ObjectParameter("lib_id", lib_id) :
                new ObjectParameter("lib_id", typeof(int));
    
            var lib_nomParameter = lib_nom != null ?
                new ObjectParameter("lib_nom", lib_nom) :
                new ObjectParameter("lib_nom", typeof(string));
    
            var aut_idParameter = aut_id.HasValue ?
                new ObjectParameter("aut_id", aut_id) :
                new ObjectParameter("aut_id", typeof(int));
    
            var gen_idParameter = gen_id.HasValue ?
                new ObjectParameter("gen_id", gen_id) :
                new ObjectParameter("gen_id", typeof(int));
    
            var lib_ediParameter = lib_edi != null ?
                new ObjectParameter("lib_edi", lib_edi) :
                new ObjectParameter("lib_edi", typeof(string));
    
            var lib_fec_pubParameter = lib_fec_pub.HasValue ?
                new ObjectParameter("lib_fec_pub", lib_fec_pub) :
                new ObjectParameter("lib_fec_pub", typeof(int));
    
            var lib_disp_stockParameter = lib_disp_stock.HasValue ?
                new ObjectParameter("lib_disp_stock", lib_disp_stock) :
                new ObjectParameter("lib_disp_stock", typeof(int));
    
            var edi_idParameter = edi_id.HasValue ?
                new ObjectParameter("edi_id", edi_id) :
                new ObjectParameter("edi_id", typeof(int));
    
            var lib_user_modParameter = lib_user_mod != null ?
                new ObjectParameter("lib_user_mod", lib_user_mod) :
                new ObjectParameter("lib_user_mod", typeof(string));
    
            var lib_stateParameter = lib_state.HasValue ?
                new ObjectParameter("lib_state", lib_state) :
                new ObjectParameter("lib_state", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EditarLibro", lib_idParameter, lib_nomParameter, aut_idParameter, gen_idParameter, lib_ediParameter, lib_fec_pubParameter, lib_disp_stockParameter, edi_idParameter, lib_user_modParameter, lib_stateParameter);
        }
    
        public virtual int usp_EditarPersonal(Nullable<int> per_id, string per_nom, string per_ape_pat, string per_ape_mat, string per_dir, string ubg_id, string per_dni, string per_tel, string per_mail, string per_pass, byte[] per_foto, Nullable<System.DateTime> per_fec_ing, string per_user_mod, Nullable<bool> per_state)
        {
            var per_idParameter = per_id.HasValue ?
                new ObjectParameter("per_id", per_id) :
                new ObjectParameter("per_id", typeof(int));
    
            var per_nomParameter = per_nom != null ?
                new ObjectParameter("per_nom", per_nom) :
                new ObjectParameter("per_nom", typeof(string));
    
            var per_ape_patParameter = per_ape_pat != null ?
                new ObjectParameter("per_ape_pat", per_ape_pat) :
                new ObjectParameter("per_ape_pat", typeof(string));
    
            var per_ape_matParameter = per_ape_mat != null ?
                new ObjectParameter("per_ape_mat", per_ape_mat) :
                new ObjectParameter("per_ape_mat", typeof(string));
    
            var per_dirParameter = per_dir != null ?
                new ObjectParameter("per_dir", per_dir) :
                new ObjectParameter("per_dir", typeof(string));
    
            var ubg_idParameter = ubg_id != null ?
                new ObjectParameter("ubg_id", ubg_id) :
                new ObjectParameter("ubg_id", typeof(string));
    
            var per_dniParameter = per_dni != null ?
                new ObjectParameter("per_dni", per_dni) :
                new ObjectParameter("per_dni", typeof(string));
    
            var per_telParameter = per_tel != null ?
                new ObjectParameter("per_tel", per_tel) :
                new ObjectParameter("per_tel", typeof(string));
    
            var per_mailParameter = per_mail != null ?
                new ObjectParameter("per_mail", per_mail) :
                new ObjectParameter("per_mail", typeof(string));
    
            var per_passParameter = per_pass != null ?
                new ObjectParameter("per_pass", per_pass) :
                new ObjectParameter("per_pass", typeof(string));
    
            var per_fotoParameter = per_foto != null ?
                new ObjectParameter("per_foto", per_foto) :
                new ObjectParameter("per_foto", typeof(byte[]));
    
            var per_fec_ingParameter = per_fec_ing.HasValue ?
                new ObjectParameter("per_fec_ing", per_fec_ing) :
                new ObjectParameter("per_fec_ing", typeof(System.DateTime));
    
            var per_user_modParameter = per_user_mod != null ?
                new ObjectParameter("per_user_mod", per_user_mod) :
                new ObjectParameter("per_user_mod", typeof(string));
    
            var per_stateParameter = per_state.HasValue ?
                new ObjectParameter("per_state", per_state) :
                new ObjectParameter("per_state", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EditarPersonal", per_idParameter, per_nomParameter, per_ape_patParameter, per_ape_matParameter, per_dirParameter, ubg_idParameter, per_dniParameter, per_telParameter, per_mailParameter, per_passParameter, per_fotoParameter, per_fec_ingParameter, per_user_modParameter, per_stateParameter);
        }
    
        public virtual ObjectResult<usp_EditorialesMasAlquiladas_Result> usp_EditorialesMasAlquiladas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_EditorialesMasAlquiladas_Result>("usp_EditorialesMasAlquiladas", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<usp_FiltrarLibrosxPeriodo_Result> usp_FiltrarLibrosxPeriodo(Nullable<int> gen_id, Nullable<int> aut_id, Nullable<System.DateTime> fecIn, Nullable<System.DateTime> fecEn)
        {
            var gen_idParameter = gen_id.HasValue ?
                new ObjectParameter("gen_id", gen_id) :
                new ObjectParameter("gen_id", typeof(int));
    
            var aut_idParameter = aut_id.HasValue ?
                new ObjectParameter("aut_id", aut_id) :
                new ObjectParameter("aut_id", typeof(int));
    
            var fecInParameter = fecIn.HasValue ?
                new ObjectParameter("fecIn", fecIn) :
                new ObjectParameter("fecIn", typeof(System.DateTime));
    
            var fecEnParameter = fecEn.HasValue ?
                new ObjectParameter("fecEn", fecEn) :
                new ObjectParameter("fecEn", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_FiltrarLibrosxPeriodo_Result>("usp_FiltrarLibrosxPeriodo", gen_idParameter, aut_idParameter, fecInParameter, fecEnParameter);
        }
    
        public virtual ObjectResult<usp_GenerosMasSolicitados_Result> usp_GenerosMasSolicitados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GenerosMasSolicitados_Result>("usp_GenerosMasSolicitados");
        }
    
        public virtual int usp_InsertarAutor(string aut_nom, string aut_ape, string aut_pais, byte[] aut_foto, string aut_user_reg)
        {
            var aut_nomParameter = aut_nom != null ?
                new ObjectParameter("aut_nom", aut_nom) :
                new ObjectParameter("aut_nom", typeof(string));
    
            var aut_apeParameter = aut_ape != null ?
                new ObjectParameter("aut_ape", aut_ape) :
                new ObjectParameter("aut_ape", typeof(string));
    
            var aut_paisParameter = aut_pais != null ?
                new ObjectParameter("aut_pais", aut_pais) :
                new ObjectParameter("aut_pais", typeof(string));
    
            var aut_fotoParameter = aut_foto != null ?
                new ObjectParameter("aut_foto", aut_foto) :
                new ObjectParameter("aut_foto", typeof(byte[]));
    
            var aut_user_regParameter = aut_user_reg != null ?
                new ObjectParameter("aut_user_reg", aut_user_reg) :
                new ObjectParameter("aut_user_reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAutor", aut_nomParameter, aut_apeParameter, aut_paisParameter, aut_fotoParameter, aut_user_regParameter);
        }
    
        public virtual int usp_InsertarCliente(string cli_nom, string cli_ape, string cli_dir, string cli_tel, string cli_mail, string cli_dni, string ubg_id, Nullable<System.DateTime> cli_fec_nac, string cli_sex, byte[] cli_foto, string cli_user_reg)
        {
            var cli_nomParameter = cli_nom != null ?
                new ObjectParameter("cli_nom", cli_nom) :
                new ObjectParameter("cli_nom", typeof(string));
    
            var cli_apeParameter = cli_ape != null ?
                new ObjectParameter("cli_ape", cli_ape) :
                new ObjectParameter("cli_ape", typeof(string));
    
            var cli_dirParameter = cli_dir != null ?
                new ObjectParameter("cli_dir", cli_dir) :
                new ObjectParameter("cli_dir", typeof(string));
    
            var cli_telParameter = cli_tel != null ?
                new ObjectParameter("cli_tel", cli_tel) :
                new ObjectParameter("cli_tel", typeof(string));
    
            var cli_mailParameter = cli_mail != null ?
                new ObjectParameter("cli_mail", cli_mail) :
                new ObjectParameter("cli_mail", typeof(string));
    
            var cli_dniParameter = cli_dni != null ?
                new ObjectParameter("cli_dni", cli_dni) :
                new ObjectParameter("cli_dni", typeof(string));
    
            var ubg_idParameter = ubg_id != null ?
                new ObjectParameter("ubg_id", ubg_id) :
                new ObjectParameter("ubg_id", typeof(string));
    
            var cli_fec_nacParameter = cli_fec_nac.HasValue ?
                new ObjectParameter("cli_fec_nac", cli_fec_nac) :
                new ObjectParameter("cli_fec_nac", typeof(System.DateTime));
    
            var cli_sexParameter = cli_sex != null ?
                new ObjectParameter("cli_sex", cli_sex) :
                new ObjectParameter("cli_sex", typeof(string));
    
            var cli_fotoParameter = cli_foto != null ?
                new ObjectParameter("cli_foto", cli_foto) :
                new ObjectParameter("cli_foto", typeof(byte[]));
    
            var cli_user_regParameter = cli_user_reg != null ?
                new ObjectParameter("cli_user_reg", cli_user_reg) :
                new ObjectParameter("cli_user_reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", cli_nomParameter, cli_apeParameter, cli_dirParameter, cli_telParameter, cli_mailParameter, cli_dniParameter, ubg_idParameter, cli_fec_nacParameter, cli_sexParameter, cli_fotoParameter, cli_user_regParameter);
        }
    
        public virtual int usp_InsertarLibro(string lib_nom, Nullable<int> aut_id, Nullable<int> gen_id, string lib_edi, Nullable<int> lib_fec_pub, Nullable<int> lib_disp_stock, Nullable<int> edi_id, string lib_user_reg)
        {
            var lib_nomParameter = lib_nom != null ?
                new ObjectParameter("lib_nom", lib_nom) :
                new ObjectParameter("lib_nom", typeof(string));
    
            var aut_idParameter = aut_id.HasValue ?
                new ObjectParameter("aut_id", aut_id) :
                new ObjectParameter("aut_id", typeof(int));
    
            var gen_idParameter = gen_id.HasValue ?
                new ObjectParameter("gen_id", gen_id) :
                new ObjectParameter("gen_id", typeof(int));
    
            var lib_ediParameter = lib_edi != null ?
                new ObjectParameter("lib_edi", lib_edi) :
                new ObjectParameter("lib_edi", typeof(string));
    
            var lib_fec_pubParameter = lib_fec_pub.HasValue ?
                new ObjectParameter("lib_fec_pub", lib_fec_pub) :
                new ObjectParameter("lib_fec_pub", typeof(int));
    
            var lib_disp_stockParameter = lib_disp_stock.HasValue ?
                new ObjectParameter("lib_disp_stock", lib_disp_stock) :
                new ObjectParameter("lib_disp_stock", typeof(int));
    
            var edi_idParameter = edi_id.HasValue ?
                new ObjectParameter("edi_id", edi_id) :
                new ObjectParameter("edi_id", typeof(int));
    
            var lib_user_regParameter = lib_user_reg != null ?
                new ObjectParameter("lib_user_reg", lib_user_reg) :
                new ObjectParameter("lib_user_reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarLibro", lib_nomParameter, aut_idParameter, gen_idParameter, lib_ediParameter, lib_fec_pubParameter, lib_disp_stockParameter, edi_idParameter, lib_user_regParameter);
        }
    
        public virtual int usp_InsertarPersonal(string per_nom, string per_ape_pat, string per_ape_mat, string per_dir, string ubg_id, string per_dni, string per_tel, string per_mail, string per_pass, byte[] per_foto, Nullable<System.DateTime> per_fec_ing, string per_user_reg)
        {
            var per_nomParameter = per_nom != null ?
                new ObjectParameter("per_nom", per_nom) :
                new ObjectParameter("per_nom", typeof(string));
    
            var per_ape_patParameter = per_ape_pat != null ?
                new ObjectParameter("per_ape_pat", per_ape_pat) :
                new ObjectParameter("per_ape_pat", typeof(string));
    
            var per_ape_matParameter = per_ape_mat != null ?
                new ObjectParameter("per_ape_mat", per_ape_mat) :
                new ObjectParameter("per_ape_mat", typeof(string));
    
            var per_dirParameter = per_dir != null ?
                new ObjectParameter("per_dir", per_dir) :
                new ObjectParameter("per_dir", typeof(string));
    
            var ubg_idParameter = ubg_id != null ?
                new ObjectParameter("ubg_id", ubg_id) :
                new ObjectParameter("ubg_id", typeof(string));
    
            var per_dniParameter = per_dni != null ?
                new ObjectParameter("per_dni", per_dni) :
                new ObjectParameter("per_dni", typeof(string));
    
            var per_telParameter = per_tel != null ?
                new ObjectParameter("per_tel", per_tel) :
                new ObjectParameter("per_tel", typeof(string));
    
            var per_mailParameter = per_mail != null ?
                new ObjectParameter("per_mail", per_mail) :
                new ObjectParameter("per_mail", typeof(string));
    
            var per_passParameter = per_pass != null ?
                new ObjectParameter("per_pass", per_pass) :
                new ObjectParameter("per_pass", typeof(string));
    
            var per_fotoParameter = per_foto != null ?
                new ObjectParameter("per_foto", per_foto) :
                new ObjectParameter("per_foto", typeof(byte[]));
    
            var per_fec_ingParameter = per_fec_ing.HasValue ?
                new ObjectParameter("per_fec_ing", per_fec_ing) :
                new ObjectParameter("per_fec_ing", typeof(System.DateTime));
    
            var per_user_regParameter = per_user_reg != null ?
                new ObjectParameter("per_user_reg", per_user_reg) :
                new ObjectParameter("per_user_reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarPersonal", per_nomParameter, per_ape_patParameter, per_ape_matParameter, per_dirParameter, ubg_idParameter, per_dniParameter, per_telParameter, per_mailParameter, per_passParameter, per_fotoParameter, per_fec_ingParameter, per_user_regParameter);
        }
    
        public virtual ObjectResult<usp_LibrosMasAlquilados_Result> usp_LibrosMasAlquilados(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string nombreLibro)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var nombreLibroParameter = nombreLibro != null ?
                new ObjectParameter("NombreLibro", nombreLibro) :
                new ObjectParameter("NombreLibro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_LibrosMasAlquilados_Result>("usp_LibrosMasAlquilados", fechaInicioParameter, fechaFinParameter, nombreLibroParameter);
        }
    
        public virtual ObjectResult<usp_ListarAutor_Result> usp_ListarAutor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAutor_Result>("usp_ListarAutor");
        }
    
        public virtual ObjectResult<usp_ListarAutorCompuesto_Result> usp_ListarAutorCompuesto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAutorCompuesto_Result>("usp_ListarAutorCompuesto");
        }
    
        public virtual ObjectResult<usp_ListarCliente_Result> usp_ListarCliente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCliente_Result>("usp_ListarCliente");
        }
    
        public virtual ObjectResult<usp_ListarClienteSimple_Result> usp_ListarClienteSimple()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarClienteSimple_Result>("usp_ListarClienteSimple");
        }
    
        public virtual ObjectResult<usp_ListarEditorial_Result> usp_ListarEditorial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEditorial_Result>("usp_ListarEditorial");
        }
    
        public virtual ObjectResult<usp_ListarGenero_Result> usp_ListarGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarGenero_Result>("usp_ListarGenero");
        }
    
        public virtual ObjectResult<usp_ListarLibro_Result> usp_ListarLibro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarLibro_Result>("usp_ListarLibro");
        }
    
        public virtual ObjectResult<usp_ObtenerRentasPorFechas_Result> usp_ObtenerRentasPorFechas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string nombreCliente)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var nombreClienteParameter = nombreCliente != null ?
                new ObjectParameter("NombreCliente", nombreCliente) :
                new ObjectParameter("NombreCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerRentasPorFechas_Result>("usp_ObtenerRentasPorFechas", fechaInicioParameter, fechaFinParameter, nombreClienteParameter);
        }
    
        public virtual ObjectResult<usp_RentasMensuales_Result> usp_RentasMensuales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RentasMensuales_Result>("usp_RentasMensuales");
        }
    
        public virtual ObjectResult<usp_RentasxGenero_Result> usp_RentasxGenero()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RentasxGenero_Result>("usp_RentasxGenero");
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaRegion_Result> usp_Ubigeo_DistritosProvinciaRegion(string idRegion, string idProvincia)
        {
            var idRegionParameter = idRegion != null ?
                new ObjectParameter("IdRegion", idRegion) :
                new ObjectParameter("IdRegion", typeof(string));
    
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaRegion_Result>("usp_Ubigeo_DistritosProvinciaRegion", idRegionParameter, idProvinciaParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasRegion_Result> usp_Ubigeo_ProvinciasRegion(string idRegion)
        {
            var idRegionParameter = idRegion != null ?
                new ObjectParameter("IdRegion", idRegion) :
                new ObjectParameter("IdRegion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasRegion_Result>("usp_Ubigeo_ProvinciasRegion", idRegionParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_Region_Result> usp_Ubigeo_Region()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_Region_Result>("usp_Ubigeo_Region");
        }
    
        public virtual ObjectResult<usp_ValidarUsuario_Result> usp_ValidarUsuario(string user, string pass)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ValidarUsuario_Result>("usp_ValidarUsuario", userParameter, passParameter);
        }
    }
}
