//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Almacen()
        {
            this.tb_Ejemplar = new HashSet<tb_Ejemplar>();
        }
    
        public int alm_id { get; set; }
        public string alm_sec { get; set; }
        public string alm_desc { get; set; }
        public string alm_user_reg { get; set; }
        public System.DateTime alm_fec_reg { get; set; }
        public string alm_user_mod { get; set; }
        public Nullable<System.DateTime> alm_fec_mod { get; set; }
        public bool alm_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ejemplar> tb_Ejemplar { get; set; }
    }
}
