//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Autor()
        {
            this.tb_Autor_aud = new HashSet<tb_Autor_aud>();
            this.tb_Libro = new HashSet<tb_Libro>();
        }
    
        public int aut_id { get; set; }
        public string aut_nom { get; set; }
        public string aut_ape { get; set; }
        public byte[] aut_foto { get; set; }
        public string aut_pais { get; set; }
        public string aut_user_reg { get; set; }
        public System.DateTime aut_fec_reg { get; set; }
        public string aut_user_mod { get; set; }
        public Nullable<System.DateTime> aut_fec_mod { get; set; }
        public bool aut_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Autor_aud> tb_Autor_aud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Libro> tb_Libro { get; set; }
    }
}
