//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Editorial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Editorial()
        {
            this.tb_Libro = new HashSet<tb_Libro>();
            this.tb_Requerimiento = new HashSet<tb_Requerimiento>();
        }
    
        public int edi_id { get; set; }
        public string edi_nom { get; set; }
        public string edi_dir { get; set; }
        public string ubg_id { get; set; }
        public string edi_tel { get; set; }
        public string edi_mail { get; set; }
        public string edi_user_reg { get; set; }
        public Nullable<System.DateTime> edi_fec_reg { get; set; }
        public string edi_user_mod { get; set; }
        public Nullable<System.DateTime> edi_fec_mod { get; set; }
        public bool edi_state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Libro> tb_Libro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Requerimiento> tb_Requerimiento { get; set; }
        public virtual tb_Ubigeo tb_Ubigeo { get; set; }
    }
}
