//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Libro()
        {
            this.tb_Ejemplar = new HashSet<tb_Ejemplar>();
            this.tb_Requerimiento_detalle = new HashSet<tb_Requerimiento_detalle>();
        }
    
        public int lib_id { get; set; }
        public string lib_nom { get; set; }
        public Nullable<int> aut_id { get; set; }
        public Nullable<int> gen_id { get; set; }
        public string lib_edi { get; set; }
        public Nullable<int> lib_fec_pub { get; set; }
        public int lib_disp_stock { get; set; }
        public int edi_id { get; set; }
        public string lib_user_reg { get; set; }
        public System.DateTime lib_fec_reg { get; set; }
        public string lib_user_mod { get; set; }
        public Nullable<System.DateTime> lib_fec_mod { get; set; }
        public bool lib_state { get; set; }
    
        public virtual tb_Autor tb_Autor { get; set; }
        public virtual tb_Editorial tb_Editorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Ejemplar> tb_Ejemplar { get; set; }
        public virtual tb_Genero tb_Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Requerimiento_detalle> tb_Requerimiento_detalle { get; set; }
    }
}
