//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Requerimiento_detalle
    {
        public int req_id { get; set; }
        public int lib_id { get; set; }
        public int lib_cant_sol { get; set; }
        public string req_det_user_reg { get; set; }
        public System.DateTime req_det_fec_reg { get; set; }
        public string req_det_user_mod { get; set; }
        public Nullable<System.DateTime> req_det_fec_mod { get; set; }
    
        public virtual tb_Libro tb_Libro { get; set; }
        public virtual tb_Requerimiento tb_Requerimiento { get; set; }
    }
}
