//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Renta
    {
        public int rent_id { get; set; }
        public int cli_id { get; set; }
        public int ejem_id { get; set; }
        public System.DateTime rent_fec { get; set; }
        public Nullable<System.DateTime> rent_fec_dev { get; set; }
        public string rent_obs { get; set; }
        public string rent_user_reg { get; set; }
        public System.DateTime rent_fec_reg { get; set; }
        public string rent_user_mod { get; set; }
        public Nullable<System.DateTime> rent_fec_mod { get; set; }
        public bool rent_state { get; set; }
    
        public virtual tb_Cliente tb_Cliente { get; set; }
        public virtual tb_Ejemplar tb_Ejemplar { get; set; }
    }
}
