//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaRentas
    {
        public int rent_id { get; set; }
        public System.DateTime rent_fec { get; set; }
        public string cli_nom { get; set; }
        public string cli_ape { get; set; }
        public string lib_nom { get; set; }
        public string rent_obs { get; set; }
    }
}
