//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesWeb.ProxyAutor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorDC", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class AutorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorNombreApellidosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutorId {
            get {
                return this.AutorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorIdField, value) != true)) {
                    this.AutorIdField = value;
                    this.RaisePropertyChanged("AutorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutorNombreApellidos {
            get {
                return this.AutorNombreApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorNombreApellidosField, value) != true)) {
                    this.AutorNombreApellidosField = value;
                    this.RaisePropertyChanged("AutorNombreApellidos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAutor.IServicioAutor")]
    public interface IServicioAutor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutor/ObtenerAutores", ReplyAction="http://tempuri.org/IServicioAutor/ObtenerAutoresResponse")]
        LosGrisesWeb.ProxyAutor.AutorDC[] ObtenerAutores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAutor/ObtenerAutores", ReplyAction="http://tempuri.org/IServicioAutor/ObtenerAutoresResponse")]
        System.Threading.Tasks.Task<LosGrisesWeb.ProxyAutor.AutorDC[]> ObtenerAutoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAutorChannel : LosGrisesWeb.ProxyAutor.IServicioAutor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAutorClient : System.ServiceModel.ClientBase<LosGrisesWeb.ProxyAutor.IServicioAutor>, LosGrisesWeb.ProxyAutor.IServicioAutor {
        
        public ServicioAutorClient() {
        }
        
        public ServicioAutorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAutorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAutorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAutorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LosGrisesWeb.ProxyAutor.AutorDC[] ObtenerAutores() {
            return base.Channel.ObtenerAutores();
        }
        
        public System.Threading.Tasks.Task<LosGrisesWeb.ProxyAutor.AutorDC[]> ObtenerAutoresAsync() {
            return base.Channel.ObtenerAutoresAsync();
        }
    }
}
