//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesWeb.ProxyConsultas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LibroAlquilado", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class LibroAlquilado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VecesAlquiladoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VecesAlquilado {
            get {
                return this.VecesAlquiladoField;
            }
            set {
                if ((this.VecesAlquiladoField.Equals(value) != true)) {
                    this.VecesAlquiladoField = value;
                    this.RaisePropertyChanged("VecesAlquilado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ejemplar", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class Ejemplar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisponibilidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Disponibilidad {
            get {
                return this.DisponibilidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DisponibilidadField, value) != true)) {
                    this.DisponibilidadField = value;
                    this.RaisePropertyChanged("Disponibilidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Libro {
            get {
                return this.LibroField;
            }
            set {
                if ((object.ReferenceEquals(this.LibroField, value) != true)) {
                    this.LibroField = value;
                    this.RaisePropertyChanged("Libro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneroSolicitado", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class GeneroSolicitado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VecesSolicitadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VecesSolicitado {
            get {
                return this.VecesSolicitadoField;
            }
            set {
                if ((this.VecesSolicitadoField.Equals(value) != true)) {
                    this.VecesSolicitadoField = value;
                    this.RaisePropertyChanged("VecesSolicitado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditorialAlquilada", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class EditorialAlquilada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VecesAlquiladaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Editorial {
            get {
                return this.EditorialField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorialField, value) != true)) {
                    this.EditorialField = value;
                    this.RaisePropertyChanged("Editorial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VecesAlquilada {
            get {
                return this.VecesAlquiladaField;
            }
            set {
                if ((this.VecesAlquiladaField.Equals(value) != true)) {
                    this.VecesAlquiladaField = value;
                    this.RaisePropertyChanged("VecesAlquilada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Renta", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class Renta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lib_nomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime rent_fecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rent_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rent_obsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cliente {
            get {
                return this.clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.clienteField, value) != true)) {
                    this.clienteField = value;
                    this.RaisePropertyChanged("cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lib_nom {
            get {
                return this.lib_nomField;
            }
            set {
                if ((object.ReferenceEquals(this.lib_nomField, value) != true)) {
                    this.lib_nomField = value;
                    this.RaisePropertyChanged("lib_nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime rent_fec {
            get {
                return this.rent_fecField;
            }
            set {
                if ((this.rent_fecField.Equals(value) != true)) {
                    this.rent_fecField = value;
                    this.RaisePropertyChanged("rent_fec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rent_id {
            get {
                return this.rent_idField;
            }
            set {
                if ((this.rent_idField.Equals(value) != true)) {
                    this.rent_idField = value;
                    this.RaisePropertyChanged("rent_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rent_obs {
            get {
                return this.rent_obsField;
            }
            set {
                if ((object.ReferenceEquals(this.rent_obsField, value) != true)) {
                    this.rent_obsField = value;
                    this.RaisePropertyChanged("rent_obs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsultas.IServicioConsultas")]
    public interface IServicioConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerLibrosMasAlquilados", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerLibrosMasAlquiladosResponse")]
        LosGrisesWeb.ProxyConsultas.LibroAlquilado[] ObtenerLibrosMasAlquilados(System.DateTime fechaInicio, System.DateTime fechaFin, string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerLibrosMasAlquilados", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerLibrosMasAlquiladosResponse")]
        System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.LibroAlquilado[]> ObtenerLibrosMasAlquiladosAsync(System.DateTime fechaInicio, System.DateTime fechaFin, string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarEjemplaresDisponibles", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarEjemplaresDisponiblesResponse")]
        LosGrisesWeb.ProxyConsultas.Ejemplar[] ConsultarEjemplaresDisponibles(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ConsultarEjemplaresDisponibles", ReplyAction="http://tempuri.org/IServicioConsultas/ConsultarEjemplaresDisponiblesResponse")]
        System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.Ejemplar[]> ConsultarEjemplaresDisponiblesAsync(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerGenerosMasSolicitados", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerGenerosMasSolicitadosResponse")]
        LosGrisesWeb.ProxyConsultas.GeneroSolicitado[] ObtenerGenerosMasSolicitados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerGenerosMasSolicitados", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerGenerosMasSolicitadosResponse")]
        System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.GeneroSolicitado[]> ObtenerGenerosMasSolicitadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerEditorialesMasAlquiladas", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerEditorialesMasAlquiladasResponse")]
        LosGrisesWeb.ProxyConsultas.EditorialAlquilada[] ObtenerEditorialesMasAlquiladas(System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerEditorialesMasAlquiladas", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerEditorialesMasAlquiladasResponse")]
        System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.EditorialAlquilada[]> ObtenerEditorialesMasAlquiladasAsync(System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerRentasPorFechas", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerRentasPorFechasResponse")]
        LosGrisesWeb.ProxyConsultas.Renta[] ObtenerRentasPorFechas(System.DateTime fechaInicio, System.DateTime fechaFin, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ObtenerRentasPorFechas", ReplyAction="http://tempuri.org/IServicioConsultas/ObtenerRentasPorFechasResponse")]
        System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.Renta[]> ObtenerRentasPorFechasAsync(System.DateTime fechaInicio, System.DateTime fechaFin, string cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultasChannel : LosGrisesWeb.ProxyConsultas.IServicioConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultasClient : System.ServiceModel.ClientBase<LosGrisesWeb.ProxyConsultas.IServicioConsultas>, LosGrisesWeb.ProxyConsultas.IServicioConsultas {
        
        public ServicioConsultasClient() {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LosGrisesWeb.ProxyConsultas.LibroAlquilado[] ObtenerLibrosMasAlquilados(System.DateTime fechaInicio, System.DateTime fechaFin, string libro) {
            return base.Channel.ObtenerLibrosMasAlquilados(fechaInicio, fechaFin, libro);
        }
        
        public System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.LibroAlquilado[]> ObtenerLibrosMasAlquiladosAsync(System.DateTime fechaInicio, System.DateTime fechaFin, string libro) {
            return base.Channel.ObtenerLibrosMasAlquiladosAsync(fechaInicio, fechaFin, libro);
        }
        
        public LosGrisesWeb.ProxyConsultas.Ejemplar[] ConsultarEjemplaresDisponibles(string libro) {
            return base.Channel.ConsultarEjemplaresDisponibles(libro);
        }
        
        public System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.Ejemplar[]> ConsultarEjemplaresDisponiblesAsync(string libro) {
            return base.Channel.ConsultarEjemplaresDisponiblesAsync(libro);
        }
        
        public LosGrisesWeb.ProxyConsultas.GeneroSolicitado[] ObtenerGenerosMasSolicitados() {
            return base.Channel.ObtenerGenerosMasSolicitados();
        }
        
        public System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.GeneroSolicitado[]> ObtenerGenerosMasSolicitadosAsync() {
            return base.Channel.ObtenerGenerosMasSolicitadosAsync();
        }
        
        public LosGrisesWeb.ProxyConsultas.EditorialAlquilada[] ObtenerEditorialesMasAlquiladas(System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ObtenerEditorialesMasAlquiladas(fechaInicio, fechaFin);
        }
        
        public System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.EditorialAlquilada[]> ObtenerEditorialesMasAlquiladasAsync(System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ObtenerEditorialesMasAlquiladasAsync(fechaInicio, fechaFin);
        }
        
        public LosGrisesWeb.ProxyConsultas.Renta[] ObtenerRentasPorFechas(System.DateTime fechaInicio, System.DateTime fechaFin, string cliente) {
            return base.Channel.ObtenerRentasPorFechas(fechaInicio, fechaFin, cliente);
        }
        
        public System.Threading.Tasks.Task<LosGrisesWeb.ProxyConsultas.Renta[]> ObtenerRentasPorFechasAsync(System.DateTime fechaInicio, System.DateTime fechaFin, string cliente) {
            return base.Channel.ObtenerRentasPorFechasAsync(fechaInicio, fechaFin, cliente);
        }
    }
}
