//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LosGrisesForm.ProxyUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbigeoDC", Namespace="http://schemas.datacontract.org/2004/07/LosGrisesServices")]
    [System.SerializableAttribute()]
    public partial class UbigeoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbigeoDesc {
            get {
                return this.UbigeoDescField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoDescField, value) != true)) {
                    this.UbigeoDescField = value;
                    this.RaisePropertyChanged("UbigeoDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbigeoId {
            get {
                return this.UbigeoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoIdField, value) != true)) {
                    this.UbigeoIdField = value;
                    this.RaisePropertyChanged("UbigeoId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ObtenerUbigeos", ReplyAction="http://tempuri.org/IServicioUbigeo/ObtenerUbigeosResponse")]
        LosGrisesForm.ProxyUbigeo.UbigeoDC[] ObtenerUbigeos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/ObtenerUbigeos", ReplyAction="http://tempuri.org/IServicioUbigeo/ObtenerUbigeosResponse")]
        System.Threading.Tasks.Task<LosGrisesForm.ProxyUbigeo.UbigeoDC[]> ObtenerUbigeosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbigeoChannel : LosGrisesForm.ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<LosGrisesForm.ProxyUbigeo.IServicioUbigeo>, LosGrisesForm.ProxyUbigeo.IServicioUbigeo {
        
        public ServicioUbigeoClient() {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LosGrisesForm.ProxyUbigeo.UbigeoDC[] ObtenerUbigeos() {
            return base.Channel.ObtenerUbigeos();
        }
        
        public System.Threading.Tasks.Task<LosGrisesForm.ProxyUbigeo.UbigeoDC[]> ObtenerUbigeosAsync() {
            return base.Channel.ObtenerUbigeosAsync();
        }
    }
}
